#!/usr/bin/env python3

import sys
import os
import subprocess

main_function_map = {}

def main_function(func):
    global main_function_map
    main_function_map[func.__name__.replace('_','-')] = func
    return func

@main_function
def airplane_mode_on(args):
    subprocess.check_call(['rfkill', 'block', 'all'])

@main_function
def airplane_mode_off(args):
    subprocess.check_call(['rfkill', 'unblock', 'all'])

def program_name():
    return os.path.basename(sys.argv[0])

def main_function_dispatch(name, args):
    try:
        f = main_function_map[name]
    except KeyError:
        sys.stderr.write('%s is not a valid command name\n' % (name,))
        sys.exit(2)
    f(args)

if __name__ == '__main__':
    main_function_dispatch(program_name(), sys.argv[1:])
