#!/usr/bin/env python3

import sys
import os
import subprocess

# Google Play Music supported file types
# https://support.google.com/googleplay/answer/1100462?hl=en

supported_extensions = set(['.mp3', '.m4a', '.wma', '.flac',
                            '.ogg', '.m4p'])

def transcode_to_mp3(filename):
    (basename, ext) = os.path.splitext(filename)
    out_filename = basename + '.mp3'
    subprocess.check_call(['ffmpeg',
                           '-y', # overwrite output files
                           '-i', filename,
                           '-acodec', 'mp3',
                           out_filename])

def main(args):
    for i in args:
        ext = os.path.splitext(i)[1]
        if ext in supported_extensions:
            continue
        try:
            transcode_to_mp3(i)
        except subprocess.CalledProcessError:
            # could be 'is a directory' when invoked with '*'
            pass

if __name__ == '__main__':
    main(sys.argv[1:])
