#!/usr/bin/env python3

# $ printf 'long get_constant() { return 0xdeadbeef; }' |  cc-compile

import sys
import os
import subprocess

def main(args):
    language_code = 'c'
    cc_cmd = os.getenv('CC', 'gcc')
    r = subprocess.call([cc_cmd,
                        '-x%c' % (language_code,),
                        '-S',
                        '-o-', # write output to STDOUT
                        '-'] + args)
    sys.exit(r)

if __name__ == '__main__':
    main(sys.argv[1:])
