#!/usr/bin/env python

import sys
import os
import subprocess

import gtk

def program_name():
    return os.path.basename(sys.argv[0])

clipboard = None

def clipboard_get_text(selection='PRIMARY'):
    'return textual data from the X11 clipboard selection'
    global clipboard
    clipboard = gtk.Clipboard(selection=selection)
    return clipboard.wait_for_text()

def print_clipboard(selection):
    sys.stdout.write(clipboard_get_text(selection))
    sys.stdout.write('\n')
    return 0

main_function_list = []

def main_function(func):
    global main_function_list
    main_function_list.append(func)
    return func

@main_function
def clipboard_primary(args):
    return print_clipboard('PRIMARY')

@main_function
def clipboard(args):
    return print_clipboard('CLIPBOARD')

@main_function
def clipboard_open_file_line(args):
    'assume input in "filename:line" (ie. grep) format, open in editor'
    (filename, line) = clipboard_get_text().strip().split(':')

    # FIXME: handle VISUAL, not all editors handle "filename +line" cmd line
    editor_cmd = os.environ.get('EDITOR', 'vim')
    return subprocess.call([ editor_cmd, filename, '+%s' % line ])

def main(args):
    def to_command_name(s):
        return s.replace('_', '-')

    name_to_function = dict( (to_command_name(x.__name__), x)
                            for x in main_function_list )
    return name_to_function[program_name()](args)

if __name__ == '__main__':
    main(sys.argv[1:])
