#!/usr/bin/env python

import sys
import os
import crypt as crypt_module
import random
import string
import optparse

def program_name():
    return os.path.basename(sys.argv[0])

main_function_list = []

def main_function(func):
    global main_function_list
    main_function_list.append(func)
    return func

def main(args):
    def to_command_name(s):
        return s.replace('_', '-')

    name_to_function = dict( (to_command_name(x.__name__), x)
                            for x in main_function_list )
    return name_to_function[program_name()](args)

def salt_gen(length):
    salt_candidates = string.letters + string.digits + './'
    return ''.join( random.choice(salt_candidates) for x in xrange(8) )

def do_crypt(pure_text, salt):
    return crypt_module.crypt(pure_text, salt)

def do_md5(pure_text, salt):
    '''Passing a "salt" that starts with "$1$" to crypt(3)
    will use an md5 based crypt algorithm,
    works at least with glibc on a linux system'''
    return crypt_module.crypt(pure_text, '$1$' + salt)

def crypt_main(args, salt_len, crypt_func):
    global crypt_options
    op = optparse.OptionParser(usage='usage: %prog [ OPTIONS ]\n'
                     'input is read from the "PASSWORD" environment variable', option_list = [
        optparse.Option('--salt', default=None),
    ])
    (options, args) = op.parse_args(args)
    pure_text = os.environ.get('PASSWORD')
    if args or (pure_text is None):
        op.print_usage()
        sys.exit(2)
    if options.salt is not None and len(options.salt) != salt_len:
        sys.stderr.write('%s: salt length must be %d not %d\n' % (program_name(),
                                                                  salt_len, len(options.salt)))
        sys.exit(2)
    
    if options.salt is None:
        salt = salt_gen(salt_len)
    else:
        salt = options.salt

    cipher_text = crypt_func(pure_text, salt)
    sys.stdout.write('{\n\tcipher_text: %r,\n\tsalt: %r\n}\n' % (cipher_text, salt))

@main_function
def crypt(args):
    return crypt_main(args, salt_len=2, crypt_func=do_crypt)

@main_function
def md5crypt(args):
    return crypt_main(args, salt_len=8, crypt_func=do_md5)

if __name__ == '__main__':
    main(sys.argv[1:])
