#!/usr/bin/env python

import sys
import subprocess

args = sys.argv[1:]
DICTIONARY_FILE = '/usr/share/dict/words'
# assumes DICTIONARY_FILE content is in lower case
subprocess.call(['grep', args[0].lower(), DICTIONARY_FILE])
