#!/usr/bin/env python

'''
Query Fedora build dependencies:
# Which packages have SDT tracepoints enabled?
fedora-source-query --whatrequires systemtap-sdt-devel

# NOTE: Since "sys/sdt.h" is a header only library,
# you can't get this information by querying the provies / requires in arch specific repositories

# Which packages depends on gtk3-devel to build?
fedora-source-query --whatrequires gtk3-devel

# which build dependencies does gtk3 itself have?
# Use an SRPM name here, ex: gtk3 instead of gtk3-devel
fedora-source-query --requires gtk3
'''

import sys
import os
import argparse
import subprocess

def main(args):
    op = argparse.ArgumentParser(usage='usage: %(prog)s (--requires | --whatrequires) PKG [PKG ...]')
    op.add_argument('-r', '--rawhide', action='store_true')
    (options, args) = op.parse_known_args(args)
    if not args:
        op.print_usage()
        sys.exit(2)

    if options.rawhide:
        repoid = 'rawhide-source'
    else:
        repoid = 'fedora-source'
    subprocess.check_call(['repoquery', '--repoid=' + repoid, '--archlist=src',
                          ] + args)

if __name__ == '__main__':
    main(sys.argv[1:])
