#!/bin/sh

# Audio pass through would be better than double lossy compression, e.g.
# 	ffmpeg -i INPUT-FILE -map 0:1 -acodec copy OUTPUT-FILE
# Should also preserve ID3 like metadata if possible
ffmpeg -i $1 -acodec libmp3lame $(echo $1 | sed 's|\.flv$|.mp3|')
