#!/bin/sh

# List Linux graphics stack component versions on the running system
# e.g.
# $ graphics-stack-versions
# kernel-3.7.2-204.fc18.x86_64
# mesa-dri-drivers-9.0.1-3.fc18.x86_64
# libdrm-2.4.41-1.fc18.x86_64
# xorg-x11-drv-intel-2.20.18-1.fc18.x86_64

ARCH=$(uname -p)
printf 'kernel-%s\n' $(uname -r)
# FIXME: xorg-x11-drv-XXX: hardcoding intel
# TODO: xorg: UXA or SNA (the acceleration method used)
rpm -q mesa-dri-drivers.$ARCH libdrm.$ARCH xorg-x11-drv-intel

# Search for newer builds of graphics stack components in Fedora:
# kernel: http://koji.fedoraproject.org/koji/packageinfo?packageID=8
# mesa:   http://koji.fedoraproject.org/koji/packageinfo?packageID=184
# libdrm: http://koji.fedoraproject.org/koji/packageinfo?packageID=770
# xorg-x11-drv-intel: http://koji.fedoraproject.org/koji/packageinfo?packageID=7794
