#!/usr/bin/env python3

# Merge multiple image files into one PDF
# requires:
# convert  (part of ImageMagick)
# pdfunite (part of poppler)

import sys
import os
import subprocess
import tempfile

def print_usage_exit():
    sys.stderr.write('%s IMAGE_FILE [IMAGE_FILE]... PDF_FILE\n' %
                     (program_name(),))
    sys.exit(2)

def program_name():
    return os.path.basename(sys.argv[0])

def main(args):
    if len(args) < 2:
        print_usage_exit()

    out_fname = args[-1]
    if os.path.splitext(out_fname)[1].lower() != '.pdf':
        sys.stderr.write("ERROR: output file \"%s\" doesn't end in .pdf" % (out_fname,))
        print_usage_exit()

    temp_pdfs =  []
    for i in args[:-1]:
        (tfd, tfname) = tempfile.mkstemp(suffix='.pdf')
        subprocess.check_call(['convert', i, tfname])
        os.close(tfd)
        temp_pdfs.append(tfname)

    subprocess.check_call(['pdfunite'] + temp_pdfs + [ args[-1] ])

if __name__ == '__main__':
    main(sys.argv[1:])
