#!/usr/bin/env python

# lsof-listening [-6]: list programs listening on a TCP port (e.g. servers)
# lsof-udp: list programs bound to a UDP port

import sys
import os
import subprocess
import optparse

def program_name():
    return os.path.basename(sys.argv[0])

def main(args):
    p = program_name()
    if p == 'lsof-listening':
        op = optparse.OptionParser(option_list = [
            optparse.Option('-4', '--ipv4-only', action='store_false')
        ])
        (options, args) = op.parse_args(args)
        cmd = 'sudo lsof -i -nP | grep LISTEN'
        if options.ipv4_only:
            cmd += '| grep -v IPv6'
        subprocess.check_call(cmd, shell=1)
    elif p == 'lsof-udp':
        subprocess.check_call('sudo lsof -i -nP | grep UDP', shell=1)
    else:
        assert(0)

if __name__ == '__main__':
    main(sys.argv[1:])
