#!/usr/bin/env python

import sys
import os
import subprocess
import optparse

def program_name():
    return os.path.basename(sys.argv[0])

def main(args):
    p = program_name()
    if p == 'lsof-listening':
        op = optparse.OptionParser(option_list = [
            optparse.Option('-6', '--ipv6', action='store_true')
        ])
        (options, args) = op.parse_args(args)
        cmd = 'sudo lsof -i -nP | grep LISTEN'
        if not options.ipv6:
            cmd += '| grep -v IPv6'
        subprocess.check_call(cmd, shell=1)
    elif p == 'lsof-udp':
        subprocess.check_call('sudo lsof -i -nP | grep UDP', shell=1)
    else:
        assert(0)

if __name__ == '__main__':
    main(sys.argv[1:])
