#!/bin/bash

if [ "$PASSWORD" = '' ]; then
	printf 'pdf-remove-password: set PASSWORD environment variable without leaving shell history\n' >&2
	exit 2
fi
case $# in
1) PDF_FILE=$1 ;;
*) printf 'usage: pdf-remove-password PDF_FILE' >&2 ; exit 2 ;;
esac
qpdf --password=$PASSWORD --decrypt "$PDF_FILE" "$(echo $PDF_FILE | sed 's|\..*$||')"-password-removed.pdf
