#!/bin/bash

# SYNOPSIS:
# $  PASSWORD=<...> pdf-remove-password FILE
# $  PASSWORD=<...> pdf-add-password FILE

pdf-remove-password() {
	if [ "$PASSWORD" = '' ]; then
		printf 'pdf-remove-password: set PASSWORD environment variable without leaving shell history\n' >&2
		return 2
	fi
	case $# in
	1) PDF_FILE=$1 ;;
	*) printf 'usage: pdf-remove-password PDF_FILE\n' >&2 ; exit 2 ;;
	esac
	qpdf --password=$PASSWORD --decrypt "$PDF_FILE" "$(echo $PDF_FILE | sed 's|\..*$||')"-password-removed.pdf
}

pdf-add-password() {
	if [ "$PASSWORD" = '' ]; then
		printf 'pdf-add-password: set PASSWORD environment variable without leaving shell history\n' >&2
		return 2
	fi
	case $# in
	1) PDF_FILE=$1 ;;
	*) printf 'usage: pdf-add-password PDF_FILE\n' >&2 ; exit 2 ;;
	esac
	OWNER_PASSWORD="$PASSWORD"
	USER_PASSWORD="$PASSWORD"
	NBITS=256
	qpdf --encrypt $OWNER_PASSWORD $USER_PASSWORD $NBITS  -- "$PDF_FILE" "$(echo $PDF_FILE | sed 's|\..*$||')"-password-added.pdf
}

case $(basename $0) in
pdf-remove-password) pdf-remove-password "$@" ;;
pdf-add-password) pdf-add-password "$@" ;;
esac
