#!/usr/bin/env python

import sys
import os
import optparse
import random

def random_files(path, n):
    l = os.listdir(path)
    while n > 0:
        try:
            i = random.choice(l)
        except IndexError:
            # l is empty
            return
        t = os.path.join(path, i)
        if not os.path.isdir(t):
            yield t
            n -= 1
        for (root, dirs, files) in os.walk(t):
            for j in files:
                yield os.path.join(root, j)
                n -= 1
        l.remove(i)

def main(args):
    op = optparse.OptionParser(usage='usage: %prog [ OPTIONS ] [ DIR ]', option_list=[
        optparse.Option('-n', type=int, default=1, help='pick N files at random'),
    ])

    (options, args) = op.parse_args(args)

    if len(args) == 0:
        path = os.getcwd()
    elif len(args) == 1:
        path = args[0]
    else:
        op.print_usage()
        sys.exit(2)

    l = list(random_files(path, options.n))
    l.sort()
    for i in l:
        sys.stdout.write('%s\n' % (i,))

if __name__ == '__main__':
    main(sys.argv[1:])
