#!/usr/bin/env python
import os
import sys

if len(sys.argv) != 2:
    sys.stderr.write('Usage: realpath PATH\n')
    sys.exit(2)
# NOTE: "readlink -f PATH" als works
sys.stdout.write(os.path.realpath(sys.argv[1])+'\n')
