#!/usr/bin/env python

import sys
sys.stderr.write('rpm-name-strip-version: not yet finished\n')
sys.exit(17)

def rpm_name_strip_version(n):
    l = len(n)
    for i in xrange(l, -1, -1):
        n[i].isdigit()

rpm_name_strip_version('abc-1')
