#!/usr/bin/env python

import sys
import os
import subprocess
import errno

def main(args):
    pwd = os.getcwd()
    cmd = [
        'rpmbuild',
        '--define', '_sourcedir ' + pwd,
        '--define', '_specdir ' + pwd,
        '--define', '_builddir ' + pwd,
        '--define', '_srcrpmdir ' + pwd,
        '--define', '_rpmdir ' + pwd, ]
    cmd.extend(args)
    r = subprocess.call(cmd)
    sys.exit(r)

if __name__ == '__main__':
    main(sys.argv[1:])
