#!/usr/bin/env python

import sys
import os
import subprocess
import tempfile

# Designed to be used during RPM packaging reviews:
# $ cd ~/rpmbuild
# $ rpmlint-pattern 'MYPACKAGE*'
# (does the equivalant of "find -name 'MYPACKAGE*.rpm' | xargs rpmlint")

def print_usage_exit():
    sys.stderr.write('usage: %s RPM-NAME-PATTERN\n')
    sys.exit(2)

def main(args):
    if not args:
        print_usage_exit()
    results = []
    for pattern in args:
        tf = tempfile.TemporaryFile(mode='w+')
        subprocess.check_call(['find', '-name', pattern + '.rpm'], stdout=tf)
        tf.seek(0)
        r = subprocess.call(['xargs', 'rpmlint'], stdin=tf)
        results.append(r)
    if all(x == 0 for x in results):
        sys.exit(0)
    else:
        sys.exit(3)

if __name__ == '__main__':
    main(sys.argv[1:])
