#!/usr/bin/env python

import sys
import os
import errno

def file_size(filename):
    try:
        return os.stat(filename).st_size
    except OSError, e:
        if e.errno == errno.ENOENT:
            return 0
        else:
            raise

sys.stdout.write('%d\n' % sum(file_size(x[:-1]) for x in sys.stdin))
