#!/usr/bin/env python

# slice START-INDEX [ END-INDEX ]
# print a subset of lines from STDIN like head(1) or tail(1)

import sys
import os

def program_name():
    return os.path.basename(sys.argv[0])

def print_usage_exit():
    sys.stderr.write('usage: %s START_INDEX [END_INDEX]\n' % (program_name(),))
    sys.exit(2)

if len(sys.argv) < 2 or len(sys.argv) > 3:
    print_usage_exit()

try:
    start = int(sys.argv[1])
except ValueError:
    print_usage_exit()

try:
    end = int(sys.argv[2])
except ValueError:
    print_usage_exit()
except IndexError:
    end = sys.maxint

it = enumerate(sys.stdin)

try:
    (count, line) = it.next()
    while count < start:
        (count, line) = it.next()
    while count < end:
        sys.stdout.write(line)
        (count, line) = it.next()
except StopIteration:
    sys.exit(0)
else:
    sys.exit(0)
