#!/usr/bin/env python

# Install the source code of any file from Fedora, e.g.:
# $ src-install /bin/true
# Downloads, extracts and patches the source containing /bin/true in the current working directory

import sys
import os
import glob
import optparse
import subprocess

def main(args):
    op = optparse.OptionParser(usage='usage: %prog FILE-FROM-OPERATING-SYSTEM',
                               option_list = [
                                   optparse.Option('-d', '--install-build-deps',
                                                   action='store_true',
                                                   help='install build dependencies'),
                              ])
    (options, args) = op.parse_args(args)

    try:
        (filename,) = args
    except ValueError:
        op.print_usage()
        sys.exit(2)

    p = subprocess.Popen(['rpmquery', '-f', '--queryformat', '%{name} %{sourcerpm}',
                          filename], stdout=subprocess.PIPE)
    data = p.stdout.read()
    (pkg, src_pkg) = data.split()
    p.wait()
    subprocess.check_call(['yumdownloader', '--source', pkg])
    p = subprocess.Popen(['rpmquery', '-pl', src_pkg], stdout=subprocess.PIPE)
    spec_filename = [ x[:-1] for x in p.stdout.readlines() if x.endswith('.spec\n') ][0]
    p.wait()
    pwd = os.getcwd()
    rpm_dir_defines = [
        '--define', '_sourcedir ' + pwd,
        '--define', '_specdir ' + pwd,
        '--define', '_builddir ' + pwd,
        '--define', '_srcrpmdir ' + pwd,
        '--define', '_rpmdir ' + pwd,
    ]
    subprocess.check_call(['rpm', ] + rpm_dir_defines + ['-i', src_pkg])

    rpmbuild_prepare = [ 'rpmbuild' ] + rpm_dir_defines + ['-bp', ]
    if not options.install_build_deps:
        rpmbuild_prepare.append('--nodeps')
    subprocess.check_call(rpmbuild_prepare + [spec_filename])

if __name__ == '__main__':
    main(sys.argv[1:])
