#!/bin/bash

# https://engineering.giphy.com/how-to-make-gifs-with-ffmpeg/

# Output GIF FPS
FPS=12

case $# in
1) FILENAME=$1 ;;
*) printf 'usage: video-to-gif FILE\n'>&2 ;;
esac

ffmpeg -i $FILENAME -filter_complex '[0:v] fps=12,split [a][b];[a] palettegen [p];[b][p] paletteuse' ${FILENAME%.*}.gif
