#!/usr/bin/env python

import sys
import os
import subprocess

def program_name():
    return os.path.basename(sys.argv[0])

def main(args):
    p = program_name()
    i = p.rfind('-')
    assert(i != -1)
    vm = p[:i]
    action = p[i+1:]

    valid_actions = set(['start', 'shutdown', 'resume', 'suspend'])
    if action not in valid_actions:
        sys.stderr.write('%s: invalid action "%s" must be one of %r\n' %
                         (p, action, valid_actions))
    subprocess.check_call(['sudo', 'virsh', action, vm])

if __name__ == '__main__':
    main(sys.argv[1:])
