#!/usr/bin/env python

# Change file extension to match the file type detected from content

# usage:
# $ xdg-rename-by-content FILE

import sys
import os

import xdg.Mime

if not xdg.Mime.exts:
    xdg.Mime.get_type_by_name('') # loads xdg.Mime.exts
    assert(xdg.Mime.exts)
mime_to_ext = dict( (m,e) for (e,m) in xdg.Mime.exts.iteritems() )

def rename_by_content(path):
    m = xdg.Mime.get_type_by_contents(path)
    if xdg.Mime.get_type_by_name(path) != m:
        ext = mime_to_ext.get(m, None)
        if not ext:
            return
        os.rename(path, os.path.splitext(path)[0] + '.' + ext)

def main(args):
    for i in args:
        rename_by_content(i)

if __name__ == '__main__':
    main(sys.argv[1:])
