#!/usr/bin/env python

# Start a new nested X11 session

# usage:
# $ xnest --client=twm
# $ xnest --client=xterm

import sys
import os
import optparse
import subprocess

DEBUG = 0

def which(program_name):
    p = subprocess.Popen(['which', program_name], stdout=subprocess.PIPE)
    d = p.stdout.read()[:-1] # strip '\n'
    if p.wait() != 0:
        raise ValueError('which: "%s" failed' % (program_name,))
    return d

def main(args):
    op = optparse.OptionParser(option_list = [
        optparse.Option('--client', default='metacity', help='X Client program to run'),
        optparse.Option('--server', default='Xnest', help='X Server executable (ex: X, Xnest ...)'),
        optparse.Option('--display', default=':1', help='new X Server display number (ex: :1, :2)'),
    ])

    (options, args) = op.parse_args(args)
    cmd = ['xinit', which(options.client), '--', which(options.server), options.display]
    if DEBUG:
        sys.stderr.write('%r\n' % (cmd,))
    subprocess.check_call(cmd)

if __name__ == '__main__':
    main(sys.argv[1:])
