#!/bin/sh
# nogpgcheck because stand alone RPM packages typically are not signed
# and even if the package is signed we'd need to "rpm --import PUBLICKEY" first
sudo yum --nogpgcheck -y localinstall $@
